name: Build and Synth

on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Anti-tamper check
        run: git diff --exit-code
      - name: Set git identity
        run: |-
          git config user.name "Auto-bump"
          git config user.email "github-actions@github.com"
      - name: Build
        run: npm run build
      - name: Synth
        run: npx aws-cdk@next synth
      - name: Anti-tamper check
        run: git diff --exit-code